# Generated by Django 4.2 on 2026-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_booking_car_cartype_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.TextField(blank=True, null=True, verbose_name='Pickup Address'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pickup Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Return Date'),
        ),
    ]
