# Generated by Django 4.2.30 on 2026-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_booking_pickup_address_booking_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved & Active'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned & Completed')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Car Plate Number'),
        ),
    ]
