# Generated by Django 4.2.30 on 2026-05-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_booking_status_car_car_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='stock',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='Plate Number')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rentals.car', verbose_name='Car Model')),
            ],
            options={
                'verbose_name': 'Physical Vehicle',
                'verbose_name_plural': 'Physical Vehicles',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rentals.vehicle', verbose_name='Assigned Vehicle'),
        ),
    ]
