# Generated by Django 4.2.30 on 2026-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_car_car_number_remove_car_stock_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ac',
            field=models.BooleanField(default=True, verbose_name='Air Conditioning (AC)'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric (EV)', 'Electric (EV)'), ('CNG', 'CNG'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=50, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.PositiveIntegerField(default=2, verbose_name='Luggage Capacity (Bags)'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=5, verbose_name='Seats Count'),
        ),
    ]
