# Generated by Django 4.2.30 on 2026-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_car_ac_car_fuel_type_car_luggage_car_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_under_maintenance',
            field=models.BooleanField(default=False, verbose_name='Under Maintenance'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Approved', 'Running'), ('Returned', 'Returned / Available'), ('Cancelled', 'Cancelled')], default='Approved', max_length=20, verbose_name='Status'),
        ),
    ]
